site_name: Lernfeld 12

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

extra_css:
    - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/KDM-LF12.git

nav:
    - Einleitung zum LF12: 'index.md'
    - Kapitel 00 - Organisatorisches: 'kapitel_00.md'
    - Kapitel 01 - Modellunternehmen: 'kapitel_01.md'
    - Kapitel 02 - Unternehmen analysieren: 'kapitel_02.md'

